In [14]:
# numpy es la libreria para hacer operaciones matematicas
import numpy as np

#Creación de matrices en python:
#matriz = [ [1,2,3,4] , [5,6,7,8] ] ---> Esta sería una matriz de 2 filas x 4 columnas

matriz = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ])

print(matriz[0])
print(matriz[1][0])
print(matriz[:2,1:])
# matriz.max(axis = 0) ----> Me muestra los valores más alto de las columnas existentes
# matriz.max(axis = 1) ----> Me muestra los valores más alto de las filas existentes

print(matriz.max(axis = 0))
print(matriz.max(axis = 1))

[1 2 3 4]
5
[[2 3 4]
 [6 7 8]]
[ 9 10 11 12]
[ 4  8 12]


In [ ]:
# pandas me permite leer archivos como CSV
import pandas as pd

# Definimos el diccionario de ejemplo
football_dicc = {
    "Player": ["Lionel Messi","Cristiano Ronaldo"],
    "year" : [2016,2016],
    "goals": [37,25],
}

data = pd.DataFrame(football_dicc)
print(data)