In [ ]:
# numpy es la libreria para hacer operaciones matematicas
import numpy as np

#Creación de matrices en python:
#matriz = [ [1,2,3,4] , [5,6,7,8] ] ---> Esta sería una matriz de 2 filas x 4 columnas

matriz = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ])

print(matriz[0])
print(matriz[1][0])
print(matriz[:2,1:])
# matriz.max(axis = 0) ----> Me muestra los valores más alto de las columnas existentes
# matriz.max(axis = 1) ----> Me muestra los valores más alto de las filas existentes

print(matriz.max(axis = 0))
print(matriz.max(axis = 1))

[1 2 3 4]
5
[[2 3 4]
 [6 7 8]]
[ 9 10 11 12]
[ 4  8 12]


In [ ]:
# pandas me permite leer archivos como CSV
import pandas as pd

# Definimos el diccionario de ejemplo
football_dicc = {
    "Player": ["Lionel Messi","Cristiano Ronaldo"],
    "year" : [2016,2016],
    "goals": [37,25],
}

data = pd.DataFrame(football_dicc)
print(data)



              Player  year  goals
0       Lionel Messi  2016     37
1  Cristiano Ronaldo  2016     25


In [ ]:
#Permisos para conectar y explorar en drive
from google.colab import drive
drive.mount('/content/drive/')

#Libreria para graficos interactivos
import plotly.express as px

path_file = "/content/drive/MyDrive/Colab Notebooks/pruebalib.csv"
#(la ruta del archivo, la separación que maneja el archivo,traiga o no la cabecera)
df=pd.read_csv(path_file,sep=",",header=0)


# df.head(n) ---> Retorna las primeras n filas (por defecto 5)
# df.tail(n) ---> Retorna las ultimas n filas (por defecto 5)
# df.sample(n) ---> Retorna n filas al azar
# df.shape ---> Devuelve el numero de filas y columnas
# df.size ---> Devuelve el total de datos (filas x columnas)
# df.info() ----> Muestra los valores no nulos, tipos de datos
# df.describe() ---> Genera estadisticas descriptivas

In [31]:
print(df.tail(2))

              Equipos;Liga
6  Manchester City;Premier
7        Liverpool;Premier


In [32]:
print(df.sample(2))

           Equipos;Liga
4  Real sociedad;Laliga
3        Sevilla;Laliga


In [33]:
print(df.shape)

(8, 1)


In [34]:
print(df.size)

8

In [35]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Equipos;Liga  8 non-null      object
dtypes: object(1)
memory usage: 192.0+ bytes


In [36]:
print(df.describe())

            Equipos;Liga
count                  8
unique                 8
top     Barcelona;Laliga
freq                   1


In [37]:
print(df.columns)

Index(['Equipos;Liga'], dtype='object')


In [43]:
#Cambio de nombre de la columna de mi archivo
df.columns = ['Equipos de futbol;Liga a la que pertenece']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype 
---  ------                                     --------------  ----- 
 0   Equipos de futbol;Liga a la que pertenece  8 non-null      object
dtypes: object(1)
memory usage: 192.0+ bytes


In [55]:
# Me trae los valores unicos
df('Equipos').unique()
# Ordenar mediante esta columna sort_values(dentro del parentesis) ó (['columna 1','columna 2'])
df.sort_values()

TypeError: 'DataFrame' object is not callable